name: Playwright Tests
on:
  push:
    branches: [ main, master, firefox_cert, chrome_cert, use_ignore_https, webServer_ignore_https, porque_no_los_dos ]
  pull_request:
    branches: [ main, master, firefox_cert, chrome_cert, use_ignore_https, webServer_ignore_https, porque_no_los_dos ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Show env
      run: npx envinfo --preset playwright

    - name: Install cert
      shell: bash
      run: |
        sudo apt install libnss3-tools
        curl -L -o mkcert "https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64"
        chmod +x mkcert
        sudo mv mkcert /usr/local/bin/mkcert
        mkcert -install
        mkdir .cert
        mkcert -key-file .cert/key.pem -cert-file .cert/cert.pem localhost

    - name: Run Playwright tests
      run: DEBUG=pw:webserver pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
